add player and enemy
mmorihiro/matchland pull request #25
Opened 2017-04-01 05:57 UTC by mmorihiro

#22

2017-04-04 09:26 UTC, forestone23 requested changes

2017-04-04 09:26 UTC, forestone23 commented on core/src/mmorihiro/larger_circle/view/ShootingView.kt
> +            setPosition(bubbleX, bubbleY)
インデントがずれてるよ。

2017-04-07 08:41 UTC, mmorihiro commented on core/src/mmorihiro/larger_circle/view/ShootingView.kt
> +            setPosition(bubbleX, bubbleY)
https://github.com/mmorihiro/larger-circle/pull/28/commits/47c4b8ba9d09c5d952c71dff53cb7c533d26aa33#diff-1ed7f55f4b6df04627c38e0e197219dcL35

2017-04-07 09:16 UTC, forestone23 approved these changes

2017-04-07 09:16 UTC, merged

2017-04-07 09:17 UTC, mmorihiro commented
:+1: